apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: test-app
    type: frontend
  annotations:
    testFiled: test
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80
    command: ["/bin/sh", "-c"]
    args: ["shuf -i 0-100 -n 1 >> /opt/number.out"]
    volumeMounts:
    - mountPath: /opt
      name: data-volume
  volumes:
  - name: data-volume
    hostPath:
      path: /data
      type: Directory
  - name: data-volume-aws
    awsElasticBlockStore:
      volumeID: ID
      fsType: ext4