apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
  labels:
    app: test
spec:
  template:
    metadata:
      name: test
      labels:
        app: test-app
        type: frontend
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: frontend