apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elasticsearch
  labels:
    app: test
  namespace: kube-system
spec:
  template:
    metadata:
      name: elasticsearch
      labels:
        app: test-app
        type: es
    spec:
      containers:
      - name: elasticsearch
        image: k8s.gcr.io/fluentd-elasticsearch:1.20
  selector:
    matchLabels:
      type: es