apiVersion: v1
kind: Config
current-context: default
clusters:
- name: demo
  cluster:
    server: https://my-master:6443
    certificate-authority-data: <base64 certificate>
contexts:
- name: default
  context:
    cluster: demo
    user: demo-admin
users:
- name: demo-admin
  user:
    client-certificate-data: <base64 certificate>
    client-key-data: <base64 key>