apiVersion: v1
kind: Config
current-context: default
clusters:
- name: demo
  cluster:
    server: https://my-master:6443
    certificate-authority: /etc/kubernetes/pki/ca.crt
contexts:
- name: default
  context:
    cluster: demo
    user: demo-admin
users:
- name: demo-admin
  user:
    client-certificate: /home/demo-admin/pki/admin.crt
    client-key: /home/demo-admin/pki/admin.key