apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  signerName: kubernetes.io/kube-apiserver-client
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXZybVNMdE5WOGpqM0gzaUdnanI3amROMXJTZDlITDBqSG1kT2N6QUkvakVDCjRIVURNeWJRKzJ6ZGhjRHFtam1lQkNrRFNFLzk4RmNwd01RK3BZMzM3dW9SVkw2Unk1R1JlYXBNeXRacml3YzcKb0owTXZORG11eU14SGhyNXBucVE5dC9pN25pT2M5V1ZBN09IR1hITE5wYlB2RmlCMk9pcjc4YmNQM2htMW9MNwpsaFEycE5hVi9nN2dEeUhaWmptMUNuaU52MHI3ZHZadzM1dmNJOGREMTdJQStNOUtrVWRhdjllZklxVnFndXRjClJBbVNLVjVWYXJnZ2F4N2dOUWo3ek03dW1NTmhFWDc0OERiREZEUTBoZVJvUUkzcm9yNzRZZ211eTR5eXdzcXUKODZ2ZlNtZEo0TDZITTdtSWh1a0JrQmNCMGhrL1psY1o0cUhobWVEME13SURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBRVFvWXQvcUZpNmRYL0tkRVlqVTdIL1FsdXVNQjdBRmNyNWtxMlU3bCtEWHV4L3NXYkZSCkdLRUtuSWFYTmMySlVXbG80SDdCYjZFNCt5d3BPenBjbjUybTN2L3FNbi9TNEtNRktRa200Tk5xcGdtSVRFNm8KbXpkS0NucjMwRThhSGF5dXIycDhEc1c2ajFJNlFkTGc3a29vbHR5b3A0bTdSOVJyY3Iyc2o2QWhmVEpaQkJnYgpwVVNENWJDaTJJZjlXaUdHNmtiUzB6WURxWVEvMjN3WFh5c2lZaENkRjRTcjVLSG5qdW55aHdVaUdaSzNyWE9uCk81NW1LSVRnamg5TmwzKy8wM2tMZmZZTjZCZUFrekRqT2NJNTNmTUkyamNhNTNrQ3pPN0Y3YnVxaFFuQlFjRnMKREQ2dkR0cEZuM21QMGcrdzBCYzFheGZiRGw3NXpVTCtNU009Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages:
  - digital signature
  - key encipherment
  - server auth