apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: test-app
    type: frontend
  annotations:
    testFiled: test
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
      - containerPort: 80
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "seq"
            operator: "In"
            values:
            - "second"
          - key: "size"
            operator: "In"
            values:
            - "large"