apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: test-app
    type: frontend
  annotations:
    testFiled: test
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
      - containerPort: 80
  tolerations:
    - key: "test"
      operator: "Equal"
      value: "test"
      effect: "NoSchedule"
      tolerationSeconds: 300