apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-test
  labels:
    app: test
spec:
  template:
    metadata:
      name: test
      labels:
        app: test-app
        type: frontend
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 3